### PR TITLE
usage of mappings functions

### PR DESCRIPTION
**Pull request by zolabar**
@im-AMS , may be you can fix the conflicts?

### CODE REVIEW

**Comment by zolabar** [comment]
@im-AMS , one just needs to take the new versions of

conformalMaps/grids.py
example.ipynb

....

however, its not that simple...

**Comment by im-AMS** [comment]
Oh no no, If you do it by doing changes on your master and merging with experimental, its bound to break things. U need to do all final changes from the latest commit from MY experimental, and then send the pullrequest.

Later for which Ill merge it to master. and u can pull changes to your repo.

**Comment by zolabar** [comment]
@im-AMS, ok, I ll see which is the best PR way…

**Comment by zolabar** [comment]
@im-AMS , I made a new PR, from a fork direclty of the experimental branch.

I suggest to comment the „pip ..“ lines in rhe example.ipynb, since users that try the examples via binder already have the packages.

Further, people like „us“ have everything installed already and those, who want to test everything locally (not with binder) might install the requirements.txt before opening „example.ipynb“ and those users who want to install the packages via example.ipynb may just uncomment the lines 😉

**Comment by zolabar** [comment]
@im-AMS , thank you for the merge, very productive collaboration!

**Comment by im-AMS** [comment]
my Pleasure!
Ill soon be merging with the main branch! Damn excited!

**Pull request closed without merging**
