### PR TITLE
Link to voila rendered binder cloud computing

### PR DESCRIPTION
**Pull request by zolabar**
Added a link that opens example_voila.ipynb (without installations directives) automatically in voila rendered style, i.e. full screen and without code, and automatically pre-run cells. This is good for users not acquainted with Python.

(circle not optimally rendered jet)

Voila-Binder Link still pointing to my forked branch, @im-AMS, you can adapt that after accepting the merge, since you need an example.ipynb without installation directives for that.

### CODE REVIEW

**Comment by zolabar** [comment]
@im-AMS, thank you for the merge.

Could you please include your names into the citation.cff file?

thank you!

did try the voila link? One may need to reload the page sometimes

**Comment by im-AMS** [comment]
Yea Thanks for the amazing work! looks amazing. 
I have added my name into the citation.
Also I noticed the ticks of the graphs seems screwed up(Donut, circle, complicated functions, NOTE they work just fine if I run example.ipynb locally)

**Comment by zolabar** [comment]
@im-AMS , thank you for the Feedback.

in my case, they work well if i reload the page once or twice, after the voila page is open.

is that reproduceable by you?

**Comment by im-AMS** [comment]
Ohh yea, my bad refreshing helps!
by the way how do I set the executing repo for voila?

**Comment by zolabar** [comment]
@im-AMS in the readme.md there are two binder links with binder icon/badget

one of those links has voila in the url and points to the ipynb that should opened with voila

the example_voila.ipynb is appropriate for that

careful: the ipynb that is ioened by voila can not contain pip installation directives

all installation directives or packages should be in the requirements.txt

i think that cloud Computing is the future, users may not download the files

**Comment by im-AMS** [comment]
got it!
 yes absolutely! damn convenient!

**Comment by zolabar** [comment]
citation_cff

@im-AMS , could you check the format of the citation.cff? The button "Cite this repository" does not work (see attached figure)

in my branch it still works, maybe one more information is missing?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by zolabar** [comment]
@im-AMS , see PR

Documentation update and citation.cff update
#16 opened 18 seconds ago by zolabar

**Pull request merged**
