### PR TITLE
experiments on sliders

### PR DESCRIPTION
**Pull request by zolabar**
experimental.ipynb has a good position of the sliders, however, the figure is not rendered anymore...

@im-AMS , you could test experimental.ipynb and give feedback, may be you see the root of the problem

interactive_plot.children[-1] is the plot, but it is not rendered...

### CODE REVIEW

**Comment by im-AMS** [comment]
Thats really weird.

for the 2nd cell, I am getting the same format output as before(the current stable output format) below which I am getting sliders in a row and a plot below it.

for the 3rd cell Im just getting row of sliders, and no graphs.

The main root for all the problem is that we use `fig.show(config={'scrollZoom': True})` in all the functions of elementary geometry.
If we manage to NOT use `fig.show` in each method `widgets.interactive()` will NOT display the graph until told.
I actually tried doing it (the update which i sent you the other day), but plotly actually tries plotting each line individually!( it looks like grids are being drawn, I could see Hline and Vline being drawn due to the delay, which I believe is intentional of plotly api)
Hence I asked if you could figure out using `batch_update` or something like [this](https://community.plotly.com/t/controlling-animation-speed-using-graph-objects-in-python/41038) apparently it is the solution to the delay problem.
if we manage to use it, we can arrange all the widgets at our will
Hence its best we try to figure out how to use it, then everything will fall in place.

**Comment by zolabar** [comment]
Ok! Thanks for feedback

**Comment by zolabar** [comment]
@im-AMS, I made some experiments with the observe attribute, as in 

https://plotly.com/python/figurewidget-app/

and it worked for a "representative" small example, partial sums of sine, however, I haven't managed to adapt the conformalMaps functions to that method. May be it inspires you? Here is the code:

class plot():
    
    def __init__(self, preWidgetN):
        
        self.N = preWidgetN
        
        x,y,n ,k = sym.symbols('x, y,n,k', real=True)
        X=np.linspace(0, 10, 100)
        
        f = sym.Sum((-1)**k*(x**(2*k+1))/(sym.factorial(2*k+1)),(k,0, n))
        f = f.subs(n, N.value)
        f = sym.lambdify(x, f)
        self.trace1 = go.Scatter(x=X, y=np.sin(X),
                            mode='lines+markers',
                            name='sin'
                               )
        self.trace2 = go.Scatter(x=X, y=f(X),
                            mode='lines',
                            name='sin-series till {0}'.format(self.N.value)
                               )

        self.fig = go.FigureWidget(data=[self.trace1, self.trace2], layout = go.Layout(template='plotly_dark'))
        
        #print(self.N)
        #print(self.N.value)

    def sineSeries(self, change):

        x,y,n ,k = sym.symbols('x, y,n,k', real=True)
        X=np.linspace(0, 10, 100)
        f = sym.Sum((-1)**k*(x**(2*k+1))/(sym.factorial(2*k+1)),(k,0, n))
        f = f.subs(n, N.value)
        f = sym.lambdify(x, f)

        trace1 = go.Scatter(x=X, y=np.sin(X),
                        mode='lines+markers',
                        name='sin')
        trace2 = go.Scatter(x=X, y=f(X),
                        mode='lines',
                        name='sin-series till {0}'.format(N.value))


        with self.fig.batch_update():
            self.fig.data[0].x = X
            self.fig.data[0].y = np.sin(X)
            self.fig.data[0].mode = 'lines+markers'
            self.fig.data[0].name = 'sin'
            self.fig.data[1].x = X
            self.fig.data[1].y = f(X)
            self.fig.data[1].mode = 'lines'
            self.fig.data[1].name = 'sin-series till {0}'.format(N.value)

        return 
    
    def show(self):
        self.N.observe(self.sineSeries, names='value')
        display(self.N, self.fig)
        return

# usage:

N = widgets.IntSlider(min=0, max=20, step=1, value=0, description='partial sum order')

p = plot(N)

p.show()

Looking forward for feedback! May be this is the way, the example from


https://plotly.com/python/figurewidget-app/


shows, that with this method, all kinds of VBoxes and HBoxes work

**Comment by im-AMS** [comment]
sure will have a look at it!

**Comment by zolabar** [comment]
@im-AMS , enclosed you find the corresponding notebook

[sine_interactive.zip](https://github.com/im-AMS/Conformal-Maps/files/7090755/sine_interactive.zip)

**Comment by im-AMS** [comment]
for some reason the plot dosent update(I dont see any change in the plot)

**Comment by zolabar** [comment]
Did you try the ipynb from the zip file?

**Comment by zolabar** [comment]
Between 10 and 20 there is no change, there the partial sums approximate sine good enough between 0 and 10.

however, between 0 and 10 there should be changes. Please try the version from the zip file. If that doesnt work, please tell me!

**Comment by zolabar** [comment]
@im-AMS , did the version from the zip file work?

**Comment by im-AMS** [comment]
@zolabar I actually executed the zip version itself

**Comment by im-AMS** [comment]
@zolabar for some reason when I restarted it appears to be working 😅

**Comment by zolabar** [comment]
💪

**Comment by im-AMS** [comment]
[RectangleInteractive.ipynb.zip](https://github.com/im-AMS/Conformal-Maps/files/7092760/RectangleInteractive.ipynb.zip)

I tried Experimenting with a brand new method. The graph works fine. But its not interacting with the slider and I am not able to figure out why. Do u mind taking a look at it?

**Comment by zolabar** [comment]
Sure, however I think not today…

**Comment by im-AMS** [comment]
sure, when you are free

**Comment by zolabar** [comment]
@im-AMS, strange, all updates, but for the function itself... You have a look at this "intermediate" version...

[rectangle_updates_but_for_f.zip](https://github.com/im-AMS/Conformal-Maps/files/7097142/rectangle_updates_but_for_f.zip)

**Comment by zolabar** [comment]
@im-AMS, the attached version "works", maybe you can figure out how to reinclude the slider for the transformation (0 org. and 1 when the function is applied).

Further, we should catch the error messages during the change of the function, while tiping a new one.

Feedback is welcome!

[RectangleInteractive.zip](https://github.com/im-AMS/Conformal-Maps/files/7098893/RectangleInteractive.zip)

**Comment by zolabar** [comment]
@im-AMS, here a version with try and except, in order to ignore errors while tiping a new function

[RectangleInteractive.zip](https://github.com/im-AMS/Conformal-Maps/files/7099773/RectangleInteractive.zip)

**Comment by im-AMS** [comment]
@zolabar  after a lot of thinking and struggle, I managed to achieve it!! 🎊🎊🎊
I have created a new experimental branch.
I have created just for rectangle.
I should still  add comments, docs and animation method, and different colours for lines.

**Comment by zolabar** [comment]
✌️ Perfect! I am looking forward to seeing it!

**Comment by zolabar** [comment]
@im-AMS , it works fine, nice object oriented approach!

would you mind, keeping the manual slider, to see a user controlled deformation? Thanks!

**Comment by im-AMS** [comment]
Thanks 😄

since widgets are working as expected, It should not be any problem to couple the Play button and slider. i.e, it can do both(automatic and manual)

**Comment by zolabar** [comment]
@im-AMS , perfect! Leveraging the usage of complex calculus in education industry and research!

**Comment by zolabar** [comment]
@im-AMS , nice usage of inheritance! Of course, a square is rectangle, hehe

**Comment by zolabar** [comment]
Nice combination of play button and manual slider in one feature!

**Comment by im-AMS** [comment]
@zolabar In the recent commit on experimental branch, for some reason I dont get any error logs/tracebacks if the entered function is wrong in jupyter notebook. I also tried adding `try, except` block, still no luck. Could you have a look at it?

**Comment by zolabar** [comment]
@im-AMS , I already tested the new rectangle class and realized the fact, that there is no error message while tiping new functions, that may even be more comfortable for users. However, next time I use it, I may have a look at that

**Comment by im-AMS** [comment]
I think it's the other way around, If there is any error, the sliders and stuffs don't respond at all, it's even more annoying and hard to debug, especially if there is a missing bracket for example.

**Comment by zolabar** [comment]
@im-AMS , true, there could be confusion…

**Comment by zolabar** [comment]
@im-AMS , I dont see the reason for „ignoring „ bad tiping… I wondered already last time. I thought it was a feature, but I didn t see error handling in code…

however, great work with the object oriented approach! 

As I understand the only geometry which still has to migrated is the „single_circle“, right?

From my side it would be nice, if the function „confCheck“ from the auxiliary module survives the future merge of the current master and experimental branches

**Comment by im-AMS** [comment]
I totally forgot about the errors which was getting displayed like in the current stable, until I started poking around and having fun.

It became more obvious when I was trying out Circle. Its having a really weard behaviour, when changing the radius, I encourage you to try poking around with it. The Circle is not behaving as it should.

Once Circle starts behaving as usual, single_circle is just few lines away.

And hopefully after that, we try experimenting with how the other modules mesh with the new one.

And then MERGE IT!! to master :)

would you mind experimenting with the circle and try whats wrong?

**Comment by zolabar** [comment]
@im-AMS , ok, interesting. I just tried out the Donut and it worked well, inclusively changing the radii interactively.

ok, next time I try out the circle itself.

**Comment by im-AMS** [comment]
Donut works as it should, Even if I make it behave as a circle in notebook, i.e, setting Rin = 0 on silders.

But Circle class dosent seem to work as it should.

**Comment by zolabar** [comment]
@im-AMS ,it seems, that something from updateFunc method can not be inherited properly from Donut to Circle…, I don’t know why…

**Comment by im-AMS** [comment]
Thats really strange

**Comment by hadamard-zweistein** [comment]
@im-AMS , please test

class Circle(Donut):
    def __init__(self, w=None, r=1, fine=50, cticks=5, rticks=10, x0=0, y0=0):
        super().__init__(w, 0, r, fine, cticks, rticks, x0, y0)
        
    def updateFunc(self, w=None, r=None, fine=None, cticks=None, rticks=None, x0=None, y0=None, frame=None, scale=100):
        if r is None:
            super().updateFunc(w=w, rin=0., rout=r, fine=fine, cticks=cticks, rticks=rticks, x0=x0, y0=y0, frame=frame, scale=scale)
        else:
            super().updateFunc(w=w, rin=0., rout=r, fine=fine, cticks=cticks, rticks=rticks, x0=x0, y0=y0, frame=frame, scale=scale)
    

in analogy to the Rectangle-Square idea

**Comment by zolabar** [comment]
@im-AMS , Feedback welcome concerning the code in 1:1 analogy to the rectangle square case!

**Comment by im-AMS** [comment]
@hadamard-zweistein haa, that's interesting, the issue was caused due to the exception handler for w.
Ill update it in the next commit.

**Comment by im-AMS** [comment]
@zolabar Im sorry, I dint get you

**Comment by zolabar** [comment]
@im-AMS , that was it! Just your opinion on the @hadamard-zweistein comment

**Comment by zolabar** [comment]
@im-AMS , nice idea to inlcude the the analyticity check into the classes.

Only, I get the error:

Rectangle object has no attribute w_sympy…

**Comment by zolabar** [comment]
@im-AMS , anyway, the check_analytic() function accepts string sympy function arguments and hence can be used as one whishes, hehe

**Comment by im-AMS** [comment]
either the Rectangle Object should already be initialized, or should just pass w to the method.
Can you show how are u running it?

And the idea is to not depend on another file which has check_analytic(), its just convenient to keep it inside the class

**Comment by im-AMS** [comment]
@zolabar my bad, I had to init in the __init__ method, change already pushed :)

**Comment by zolabar** [comment]
@im-AMS , perfect! Really cool stuff, really elegant, the inheritances, from rectangle to square, donut to circle and so on

**Comment by im-AMS** [comment]
yea right!!
I shud probably stand still and think about the fact that, I have written the code and its elegant, and probably feel proud of myself ;)
Can you believe the fact that, its the 1st object oriented code I have written on my own XD, Its damn rewarding!

**Comment by zolabar** [comment]
@im-AMS , actually I can believe it, hehe.

One comment, when I initialize the rectangle with the non conformal function

2xy+i(y sin(x)-xsin(y)) i get the answer, that it is conformal.

When I give that function directly to rect.check_analytic then the answer is, that the function is not analytic, which id correct.

may be you can check initializations with non conformal functions an check if that is recognized by the analycity checker?

**Comment by im-AMS** [comment]
ha, thats interesting, I had a doubt weather the fancy function was analytic, Ill try and have a look whats the issue.
BTW, do you know any w which is NOT analytic?

**Comment by zolabar** [comment]
@im-AMS , hehe only that fancy function that you created, hehe, if I find more I let you know

**Comment by im-AMS** [comment]
@zolabar sure.
Also can u tell me all the slider values for EccentricAnnulus, Mobius transforms and others that you had written?

**Comment by im-AMS** [comment]
@zolabar  also can u make the necessary changes in `mappings.py` mainly `RectangleToEccentricAnnulus` and `ConcentricAnnulusToEccentricAnnulus` since there are shapes for rectangle and Donut, is the name `Rectangle to` and `ConcentricAnnulus` really necessary? 
Just do a proper PR  for the appropriate changes.

**Comment by zolabar** [comment]
@im-AMS ,

try this for non conformality


left = widgets.FloatSlider(min=-5, max=5, value=-1, description='left')
bottom = widgets.FloatSlider(min=-5, max=5, value=-1, description='bottom')

top = widgets.FloatSlider(min=-5, max=5, value=1, description='top')
right = widgets.FloatSlider(min=-5, max=5, value=1, description='right')

fine = widgets.IntSlider(min = 5, max = 50, value=50, description='Fine')

Hticks = widgets.IntSlider(min = 2, max = 50, value=10, description='Hticks')
Vticks = widgets.IntSlider(min = 2, max = 50, value=30, description='Vticks')


r = sym.sqrt(x**2+y**2)

f = x*(sym.sqrt(x**2+y**2-x**2*y**2))/r + sym.I*y*(sym.sqrt(x**2+y**2-x**2*y**2))/r # transforms unit square

**Comment by zolabar** [comment]
@im-AMS,
"""
@zolabar also can u make the necessary changes in mappings.py mainly RectangleToEccentricAnnulus and ConcentricAnnulusToEccentricAnnulus since there are shapes for rectangle and Donut, is the name Rectangle to and ConcentricAnnulus really necessary?
Just do a proper PR for the appropriate changes to experimental branch
"""

The naming is not so important. Annulus is the more engineering/scientific word found in papers when referring to "donut" shapes, but is the same thing.

I haven't thought of sliders for the functions in mappings.py

the content of mappings is to obtain easily the boundary values of rectangles and "donuts" when they should be tranformed to a priori fixed eccentric donuts or ellpises. The classes and methods in mappings return those boundary values for the easy shapes and provides the mappings, that make the transforms.

I don't know if the should get interactive...

**Comment by im-AMS** [comment]
@zolabar 
No No, I mean I want the `mappings.py` to be a builtin function for w. Its just making the life of the user more easier instead of typing the function in the widget, they could just init it to a variable, like done before

**Current usage**

```
R1 = 4 # inner radius of target eccentric annulus
R2 = 7.6 # outer radius of target eccentric annulus
ep = 0.7 # relative eccentricity of target eccentric annulus

trans = RectangleToEccentricAnnulus(R1, R2, ep)

.....


function = widgets.Text( value ='{0}'.format(trans.mapping(z)) , description='w : ')

....

```

**suggested usage**

```
R1 = 4 # inner radius of target eccentric annulus
R2 = 7.6 # outer radius of target eccentric annulus
ep = 0.7 # relative eccentricity of target eccentric annulus

trans = EccentricAnnulus(R1, R2, ep)

.....


function = widgets.Text( value ='{0}'.format(trans.mapping(z)) , description='w : ')

....

```

**Comment by zolabar** [comment]
@im-AMS , thank you, but I dont see the differences in the comment above? May you copy pasted the same variant?

**Comment by zolabar** [comment]
@im-AMS , here is the example with the nonconformal mapping of unit square [-1,1]x[-1,1] to a circle

[test.zip](https://github.com/im-AMS/Conformal-Maps/files/7116666/test.zip)

**Comment by im-AMS** [comment]
`RectangleToEccentricAnnulus` changes to `EccentricAnnulus`

**Comment by zolabar** [comment]
@im-AMS, I see!

The thing is, that you can get to the eccentric annulus via the rectangle and via the donut!

In engineering you may try both variants.

That is why I think, that the package conformalMapps should support and ease "all" transformations.

So that when reading a papers with different mappings to a certain geometry one can try all variants and decide which is the one that suits one best

Therefore there should still be

"ConcentricAnnulusToEccentricAnnulus" and "RectangleToEccentricAnnulus", of course, the names could get more user friendly, or everything could be restructured...

**Comment by im-AMS** [comment]
> here is the example with the nonconformal mapping of unit square [-1,1]x[-1,1] to a circle

Wow thats damn cool!!
PS manged to fix the issue, will commit soon ;)

**Comment by im-AMS** [comment]
> The thing is, that you can get to the eccentric annulus via the rectangle and via the donut! .....

I see! 
So since almost everything works now, Ill just do the commit for fix of analytic, later you just send a PR for the intended use case for the EccentricAnnulus and I shall merge it to main branch.

**Comment by im-AMS** [comment]
@zolabar I have made a commit for major changes, the final version will look similar.
You just need to send me a pull request to the intended use cases of various Annulus, the pattern of how its done is already in the file.
As soon as u send me one, I can merge with master!

**Comment by zolabar** [comment]
@im-AMS , ok! Thanks, i ll do that as soon ad I find time! Looking forward to seeing and using the new „release“, hehe

**Pull request closed without merging**
