### PR TITLE
confCheck

### PR DESCRIPTION
**Pull request by zolabar**
confCheck in module auxiliary checks of a symbolic function is conformal by checking the cauchy riemann conditions

### CODE REVIEW

**Comment by zolabar** [comment]
@im-AMS , the „bla bla bla“ part in the readme.md is a mistake, that entered in a conflict resolve while merging or fetching from upstream…

**Comment by im-AMS** [comment]
The bla bla text was intentional, since it acts as a place holder. But are u facing any issue coz of that?
could you elaborate what exactly is happening, or anything I have to change

**Comment by zolabar** [comment]
Ok! Then everything is ok!

**Comment by zolabar** [comment]
@im-AMS , i just opened a pull request, its about some ideas, in experimental.ipynb, not fully working yet

**Pull request merged**
